## Server config
server:
  port: 8090
  servlet:
    context-path: /app
## Server config
spring:
  application:
    name: pdb-app
  docker:
    compose:
      lifecycle-management: start_only
#  datasource:
#    url: jdbc:postgresql://localhost:5432/my_db
#    username: my_user
#    password: secret
## Actuator config
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env

## Logging config
logging:
  config: classpath:logback.xml
